[package]
name = "crankshaft"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
crankshaft-config = { path = "../crankshaft-config", version = "0.1.0" }
crankshaft-engine = { path = "../crankshaft-engine", version = "0.1.0" }

[dev-dependencies]
clap.workspace = true
color-eyre.workspace = true
eyre.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[features]
default = ["config", "engine"]
config = []
engine = []

[lints]
workspace = true
